/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonetizationRouteImport } from './routes/monetization'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IslamicRouteImport } from './routes/islamic'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVerificationRouteImport } from './routes/admin/verification'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonetizationRoute = MonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IslamicRoute = IslamicRouteImport.update({
  id: '/islamic',
  path: '/islamic',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/admin/verification',
  path: '/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/chats': typeof ChatsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/email': typeof EmailRoute
  '/help': typeof HelpRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tasbih': typeof TasbihRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/wali': typeof WaliRoute
  '/admin/verification': typeof AdminVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/chats': typeof ChatsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/email': typeof EmailRoute
  '/help': typeof HelpRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tasbih': typeof TasbihRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/wali': typeof WaliRoute
  '/admin/verification': typeof AdminVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/chats': typeof ChatsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/email': typeof EmailRoute
  '/help': typeof HelpRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tasbih': typeof TasbihRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/wali': typeof WaliRoute
  '/admin/verification': typeof AdminVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/chats'
    | '/delete-account'
    | '/email'
    | '/help'
    | '/islamic'
    | '/live'
    | '/login'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tasbih'
    | '/tickets'
    | '/users'
    | '/wali'
    | '/admin/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/chats'
    | '/delete-account'
    | '/email'
    | '/help'
    | '/islamic'
    | '/live'
    | '/login'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tasbih'
    | '/tickets'
    | '/users'
    | '/wali'
    | '/admin/verification'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/chats'
    | '/delete-account'
    | '/email'
    | '/help'
    | '/islamic'
    | '/live'
    | '/login'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tasbih'
    | '/tickets'
    | '/users'
    | '/wali'
    | '/admin/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  ChatsRoute: typeof ChatsRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  EmailRoute: typeof EmailRoute
  HelpRoute: typeof HelpRoute
  IslamicRoute: typeof IslamicRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MatchesRoute: typeof MatchesRoute
  MessagingRoute: typeof MessagingRoute
  ModerationRoute: typeof ModerationRoute
  MonetizationRoute: typeof MonetizationRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  TasbihRoute: typeof TasbihRoute
  TicketsRoute: typeof TicketsRoute
  UsersRoute: typeof UsersRoute
  WaliRoute: typeof WaliRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monetization': {
      id: '/monetization'
      path: '/monetization'
      fullPath: '/monetization'
      preLoaderRoute: typeof MonetizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islamic': {
      id: '/islamic'
      path: '/islamic'
      fullPath: '/islamic'
      preLoaderRoute: typeof IslamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/admin/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  ChatsRoute: ChatsRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  EmailRoute: EmailRoute,
  HelpRoute: HelpRoute,
  IslamicRoute: IslamicRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MatchesRoute: MatchesRoute,
  MessagingRoute: MessagingRoute,
  ModerationRoute: ModerationRoute,
  MonetizationRoute: MonetizationRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  TasbihRoute: TasbihRoute,
  TicketsRoute: TicketsRoute,
  UsersRoute: UsersRoute,
  WaliRoute: WaliRoute,
  AdminVerificationRoute: AdminVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
