/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MonetizationRouteImport } from './routes/monetization'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IslamicRouteImport } from './routes/islamic'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MonetizationRoute = MonetizationRouteImport.update({
  id: '/monetization',
  path: '/monetization',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IslamicRoute = IslamicRouteImport.update({
  id: '/islamic',
  path: '/islamic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats': typeof ChatsRoute
  '/islamic': typeof IslamicRoute
  '/live': typeof LiveRoute
  '/logs': typeof LogsRoute
  '/matches': typeof MatchesRoute
  '/messaging': typeof MessagingRoute
  '/moderation': typeof ModerationRoute
  '/monetization': typeof MonetizationRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chats'
    | '/islamic'
    | '/live'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chats'
    | '/islamic'
    | '/live'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/chats'
    | '/islamic'
    | '/live'
    | '/logs'
    | '/matches'
    | '/messaging'
    | '/moderation'
    | '/monetization'
    | '/notifications'
    | '/settings'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsRoute: typeof ChatsRoute
  IslamicRoute: typeof IslamicRoute
  LiveRoute: typeof LiveRoute
  LogsRoute: typeof LogsRoute
  MatchesRoute: typeof MatchesRoute
  MessagingRoute: typeof MessagingRoute
  ModerationRoute: typeof ModerationRoute
  MonetizationRoute: typeof MonetizationRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monetization': {
      id: '/monetization'
      path: '/monetization'
      fullPath: '/monetization'
      preLoaderRoute: typeof MonetizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islamic': {
      id: '/islamic'
      path: '/islamic'
      fullPath: '/islamic'
      preLoaderRoute: typeof IslamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsRoute: ChatsRoute,
  IslamicRoute: IslamicRoute,
  LiveRoute: LiveRoute,
  LogsRoute: LogsRoute,
  MatchesRoute: MatchesRoute,
  MessagingRoute: MessagingRoute,
  ModerationRoute: ModerationRoute,
  MonetizationRoute: MonetizationRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
